/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>

extern void initialise_monitor_handles(void);

int main(void)
{
	/* This message is going to be displayed via OpenOCD semihosting.
	 * Make sure the message terminates with '\n' character.
	 * set the linker arguments
	 * 		-specs=rdimon.specs -lc -lrdimon
	 * Add semihosting enable command of the openOCD
	 * 		monitor arm semihosting enable
	 * Add the below function call and prototype to main.c
	 * 		extern void initialise_monitor_handles(void);
	 * 		initialise_monitor_handles();
	 * remove syscalls.c from the project
	 */

	initialise_monitor_handles();

	printf("Hello world\n");

	for(;;);
}
